---
title: "GMM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("lcmm")
library(lcmm)
library(dplyr)
install.packages("survival")
install.packages("parallel")
library(survival)
library(parallel)
```


```{r}
dl$id <- as.factor(dl$id)

dl2 <- dl %>%
  group_by(id) %>%
  add_tally(wt = !is.na(Date))

dl_mini <- dl2 %>%
  filter(n > 20)

dl_mini$id <- as.numeric(dl_mini$id)
dl_mini$days <- as.numeric(dl_mini$days)

dl_mini <- as.data.frame(dl_mini)
```


```{r}
lcga1 <- hlme(happy ~ days, subject = "id", ng = 1, data = dl_mini) 

lcga2 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1,
                    hlme(happy ~ days, subject = "id",
                         ng = 2, data = dl_mini, mixture = ~ days)) 

lcga3 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1,
                    hlme(happy ~ days, subject = "id",
                         ng = 3, data = dl_mini, mixture = ~ days))

lcga4 <- gridsearch(rep = 100, maxiter = 10, minit = lcga1,
                    hlme(happy ~ days, subject = "id",
                         ng = 4, data = dl_mini, mixture = ~ days))

summarytable(lcga1, lcga2, lcga3, lcga4)

summary(lcga3)

summary(lcga4)
```


```{r}

```


```{r}

```


```{r}

```